### ISSUE TITLE
Collapsing margins

### ISSUE THREAD

**Issue by fab1an** [facebook/css-layout#216]
Will this layout support collapsing margins, like described here: https://css-tricks.com/what-you-should-know-about-collapsing-margins/?

**Comment by emilsjolander** [comment]
Interesting, I didn't know about this! I don't foresee css-layout supporting this though as collapsing margins don't seem to be part of the flexbox display model. You can try it yourself by editing the sample in the link you posted to use `display: flex` on the body and divs. Now margin stacks instead of collapses.

This library does not try to implement all of css but instead we focus on implementing flexbox and related properties.
