### ISSUE TITLE
css_applyLayout crack

### ISSUE THREAD

**Issue by singno** [facebook/css-layout#236]
![image](https://cloud.githubusercontent.com/assets/5654690/19830092/4c5b62f6-9e23-11e6-8c0b-d2604274a040.png)

![image](https://cloud.githubusercontent.com/assets/5654690/19830096/5b87c080-9e23-11e6-8827-969271633d7e.png)

**Comment by emilsjolander** [comment]
@dshahidehpour Can you take a look?

**Comment by gimenete** [comment]
It fails because `node->children` is NULL. The problem seems to have been introduced here https://github.com/facebook/css-layout/commit/01c2ac3369b6e403e5f7a24b91a01b7bb792eed7?diff=unified#diff-937e78d20ebabc2f92fe6f07dc70d4a3L198

Using `node->children = CSSNodeListNew(4);` in `CSSNodeInit` works for me but it's not the optimal solution.

**Comment by dshahidehpour** [comment]
Thanks for spotting! I'm adding a fix right now.

**Comment by dshahidehpour** [comment]
Just landed a fix with #ced779b25966448feb9bd792efedd29dfa6ab9e0

**Comment by gimenete** [comment]
It works! Thanks :)
