### ISSUE TITLE
Tests are failing on firefox 31.3.0

### ISSUE THREAD

**Issue by m1el** [facebook/css-layout#25]
To reproduce: open RunLayoutTests.html in firefox.

![all tests are failing in firefox](http://i.imgur.com/DCK78I2.png)

**Comment by vjeux** [comment]
Yeah, I tried to get it working on Firefox but couldn't get it to work 100% of the time so I gave up. Pull requests to fix it are more than welcome

**Comment by 1genius** [comment]
What is the problem with firefox?  I would like to try and fix the bug.

**Comment by vjeux** [comment]
If I remember correctly, it had to do with the creation of the iframe and setting css. I couldn't get the timings right.

https://github.com/facebook/css-layout/blob/master/src/Layout-test-utils.js#L52-L83

**Comment by 1genius** [comment]
Hi Christopher,

I’m writing because I need your help.  I was looking at the java code for iframe.  I would like very much to help you and other java developers on the Github site but my java is at the basic level.  I got an A+ in the basic course.  How do I get to your level?  Your program in iframe uses function but I know that methods in java start with public static void or public static int.  I would really appreciate your advice.

Thank you,
Ben
